### ISSUE TITLE
[EMAIL UNSUBSCRIBE]

### ISSUE THREAD

**Issue by jens-ox** [AtomicReact/AtomicReact#4]
Please do not crawl GitHub in order to mass-mail people about your project. Nobody likes that.

**Comment by Guihgo** [comment]
We are so sorry for inconvenience. Just send your e-mail to unsubscribe

https://docs.google.com/forms/d/e/1FAIpQLSdS5oEFzAV0AhrH6bCwiIipCViWJqiZCVhvzDeXgJe3wvQf_g/viewform?usp=sf_link

**Comment by Silic0nS0ldier** [comment]
@Guihgo Pointing to an unsubscribe link isn't good enough. If it were, everyone's inboxes would be constantly flooded with emails. I can understand wanting to get exposure, but this is not the right way to achieve it. Heck, there are laws in place designed to try and prevent this practise.

Suppose I was interested in this project, I cannot use it as doing so would validate the practise.

I strongly recommend you remove all the people scrapped from GitHub from the mailing list.

**Comment by Guihgo** [comment]
> @Guihgo Pointing to an unsubscribe link isn't good enough. If it were, everyone's inboxes would be constantly flooded with emails. I can understand wanting to get exposure, but this is not the right way to achieve it. Heck, there are laws in place designed to try and prevent this practise.
> 
> Suppose I was interested in this project, I cannot use it as doing so would validate the practise.
> 
> I strongly recommend you remove all the people scrapped from GitHub from the mailing list.

thanks for alert.
